apiVersion: apps/v1
kind: Deployment
metadata:
  name: dqs-api-deployment
  namespace: {{ .Values.namespace }}
  labels:
    app: dqs-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dqs-api
  template:
    metadata:
      labels:
        app: dqs-api
    spec:
      containers:
      - name: dqs-api-container
        image: {{ .Values.imageUri }}
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        env:
          - name: API_ALLOWED_ORIGINS
            value: {{ .Values.API_ALLOWED_ORIGINS}}
          - name: KAFKA_BOOTSTRAP_SERVERS
            value: {{ .Values.KAFKA_BOOTSTRAP_SERVERS}}
          - name: MONGO_DB_URL
            value: { { .Values.MONGO_DB_URL } }
