apiVersion: v1
kind: Service
metadata:
  name: dqs-api-service
  namespace: {{ .Values.namespace }}
spec:
  type: LoadBalancer
  selector:
    app: dqs-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080